### ISSUE TITLE
entire transcript highlighted when active

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/a11y-media-player#41]
Is there a way to make it highlight line by line? The caption file in question loads correctly if in CC mode but when in transcript mode it shows like this:
![2018-09-10_12-48-01](https://user-images.githubusercontent.com/329735/45311727-fd09cd80-b4f7-11e8-9680-1692fd660055.png)

**Comment by nikkimk** [comment]
VTT file didn't have IDs 1.0.7 fixes this by adding IDs if there are none.
