### ISSUE TITLE
dynamically added video issue w/ multiple files on the same page

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/a11y-media-player#43]
ELMS will load in the files dynamically for performance. This appears to be an issue with the loading of the files when more then one is on the page.

- place two videos on the page
- page loads, click video 2
- hit pause
- click video 1, it now plays video 2's content

Is there anything related to the element setting itself up perhaps that could cause this?

**Comment by btopro** [comment]
yes

**Comment by nikkimk** [comment]
Can no longer duplicate. I believe this was part of a larger Firefox issue that 1.1.3 resolves.
