### ISSUE TITLE
Uncaught TypeError: iframe.pauseVideo is not a function

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/a11y-media-player#48]
when hitting play/pause button on a youtube video

`Uncaught TypeError: iframe.pauseVideo is not a function`

**Comment by btopro** [comment]
hit pause while it's playing, then hit play again, it'll throw the type error. minor issue but wanted to note

**Comment by nikkimk** [comment]
Can no longer duplicate. I believe this was part of a larger Firefox issue that 1.1.3 resolves.
